apiVersion: v1
kind: Pod
metadata:
  name: chattermill-api-pod
  labels:
    app: chattermill
    component: api
spec:
  containers:
    - image: chattermill-api:0.1
      name: chattermill-api
      ports:
        - containerPort: 4000
  dnsPolicy: ClusterFirst
---
apiVersion: v1
kind: Service
metadata:
  name: chattermill-api-service
spec:
  type: NodePort
  selector:
    app: chattermill
    component: api
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30005
